# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/mmm-st',
                'doc_host': 'https://enzokro.github.io',
                'git_url': 'https://github.com/enzokro/mmm-st',
                'lib_path': 'mmm_st'},
  'syms': {'mmm_st.core': {'mmm_st.core.foo': ('core.html#foo', 'mmm_st/core.py')}}}
